import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart'; // Added for Firebase
import 'package:job_app/presentation/screens/admin/admin_screen.dart';
import 'package:job_app/presentation/screens/auth/login_screen.dart';
import 'package:job_app/presentation/screens/auth/register_screen.dart';
//import 'package:job_hop/presentation/screens/auth/register_screen.dart'; // Import RegistrationScreen
import 'package:job_app/presentation/screens/home/home_screen.dart';
import 'package:job_app/presentation/screens/messaging/messaging_screen.dart';
import 'package:job_app/presentation/screens/notifications/notification_screen.dart';
import 'package:job_app/presentation/screens/onboarding/onboarding_screen.dart';
import 'package:job_app/presentation/screens/profiles/employer_profile_screen.dart';
import 'package:job_app/presentation/screens/profiles/payment_screen.dart';
import 'package:job_app/presentation/screens/profiles/profile_screen.dart';
import 'package:job_app/presentation/screens/profiles/profile_viewer_screen.dart';
import 'package:job_app/presentation/screens/provider/auth_provider.dart';
import 'package:job_app/presentation/screens/setting/settings_screen.dart';
import 'package:provider/provider.dart';
//import 'package:job_hop/presentation/screens/provider/auth_provider.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(
    ChangeNotifierProvider(
      create: (_) => AuthProvider(),
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Job Hop',
      initialRoute: '/onboarding', // Start with onboarding
      routes: {
        '/onboarding': (context) => const OnboardingScreen(),
        '/login': (context) => const LoginScreen(),
        '/registration': (context) => const RegistrationScreen(),
        '/home': (context) => HomeScreen(username: ModalRoute.of(context)?.settings.arguments as String? ?? 'User'),
        '/profile': (context) => ProfileScreen(username: ModalRoute.of(context)?.settings.arguments as String? ?? 'User'),
        '/settings': (context) => SettingsScreen(username: ModalRoute.of(context)?.settings.arguments as String? ?? 'User'),
        '/notifications': (context) => const NotificationScreen(),
        '/messages': (context) => MessagingScreen(username: ModalRoute.of(context)?.settings.arguments as String? ?? 'User'),
        '/profile_viewer': (context) => ProfileViewerScreen(userId: ModalRoute.of(context)?.settings.arguments as String? ?? 'unknown'),
        '/employer_profile': (context) => EmployerProfileScreen(employerId: ModalRoute.of(context)?.settings.arguments as String? ?? 'unknown'),
        '/payment': (context) => PaymentScreen(
              onPaymentComplete: (method) => print('Payment completed with $method'), // Placeholder callback
            ),
        '/admin': (context) {
          // TODO: Implement role check for admin access
          // Example: bool isAdmin = await FirebaseFirestore.instance.collection('users').doc(currentUserId).get().then((doc) => doc['isAdmin'] ?? false);
          // if (!isAdmin) return HomeScreen(username: 'User');
          return const AdminScreen();
        },
      },
    );
  }
}

